"""Offline coordinate transitions, no runtime initialization required."""
from itertools import permutations, product
from pathlib import Path
from generate_pdb import SOURCE, TWIST


def main():
    ori=[]
    for digits in product(range(3), repeat=6):
        o=tuple(reversed(digits))
        ori.append(o+((-sum(o))%3,))
    lines=['/* Generated by tools/generate_transitions.py. Do not edit. */',
           '#ifndef MINIRUBIK_TRANSITIONS_H', '#define MINIRUBIK_TRANSITIONS_H',
           '#include <stdint.h>']
    for name,states,is_ori in [('permutation',list(permutations(range(7))),False),('orientation',ori,True)]:
        lookup={state:i for i,state in enumerate(states)}
        rows=[[] for _ in range(9)]
        for state in states:
            for face in range(3):
                nxt=state
                for turn in range(3):
                    nxt=tuple((nxt[SOURCE[face][i]]+TWIST[face][i])%3 if is_ori
                              else nxt[SOURCE[face][i]] for i in range(7))
                    rows[face*3+turn].append(lookup[nxt])
        lines.append(f'static const uint16_t {name}_transition[9][{len(states)}] = {{')
        for row in rows:
            lines.append('    {')
            for i in range(0,len(row),16):
                lines.append('        '+', '.join(map(str,row[i:i+16]))+',')
            lines.append('    },')
        lines.append('};')
    lines.append('#endif')
    Path(__file__).resolve().parents[1].joinpath('transition_data.h').write_text('\n'.join(lines)+'\n')
    print('Transition tables: 103842 bytes (9 * (5040 + 729) * 2)')


if __name__ == '__main__':
    main()
