"""Generate exact projected HTM distances; Python is needed only offline."""
from collections import deque
from itertools import permutations, product
from pathlib import Path

SOURCE = ((1, 4, 2, 0, 3, 5, 6), (0, 1, 2, 4, 5, 6, 3),
          (0, 2, 5, 3, 1, 4, 6))
TWIST = ((1, 2, 0, 2, 1, 0, 0), (0, 0, 0, 1, 2, 1, 2), (0,) * 7)


def distances(states, orientation):
    lookup = {s: i for i, s in enumerate(states)}
    dist = [15] * len(states)
    dist[0] = 0
    queue = deque([states[0]])
    while queue:
        state = queue.popleft()
        depth = dist[lookup[state]] + 1
        for face in range(3):
            nxt = state
            for _ in range(3):
                nxt = tuple((nxt[SOURCE[face][i]] + TWIST[face][i]) % 3
                            if orientation else nxt[SOURCE[face][i]]
                            for i in range(7))
                index = lookup[nxt]
                if dist[index] == 15:
                    dist[index] = depth
                    queue.append(nxt)
    assert max(dist) < 15
    return dist


def main():
    # Least-significant trit is o[0], matching get_orientation_index.
    orientations = []
    for digits in product(range(3), repeat=6):
        ori = tuple(reversed(digits))
        orientations.append(ori + ((-sum(ori)) % 3,))
    tables = [('orientation', distances(orientations, True)),
              ('permutation', distances(list(permutations(range(7))), False))]
    lines = ['/* Generated by tools/generate_pdb.py. Do not edit. */',
             '#ifndef MINIRUBIK_PDB_DATA_H', '#define MINIRUBIK_PDB_DATA_H',
             '#include <stdint.h>']
    for name, dist in tables:
        packed = [dist[i] | ((dist[i + 1] if i + 1 < len(dist) else 15) << 4)
                  for i in range(0, len(dist), 2)]
        lines.append(f'static const uint8_t pdb_{name}_packed[{len(packed)}] = {{')
        for i in range(0, len(packed), 16):
            lines.append('    ' + ', '.join(f'0x{x:02x}' for x in packed[i:i+16]) + ',')
        lines.append('};')
        print(f'{name}: {len(dist)} states, max distance {max(dist)}, {len(packed)} bytes')
    lines.append('#endif')
    Path(__file__).resolve().parents[1].joinpath('pdb_data.h').write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
